package com.pploder.fastconfig

import java.io.*
import java.util.*
import kotlin.reflect.KClass
import kotlin.reflect.full.memberProperties

const val defaultConfigFile = "config.properties"

abstract class FastConfig {
    init {
        if (!this.javaClass.kotlin.isData) {
            throw FastConfigException("Configuration class has to be a data class")
        }
    }

    companion object {
        fun <T : FastConfig> loadFromProperties(clazz: KClass<T>, props: Properties): T {
            val ctor = clazz.constructors.first()

            val args = ctor.parameters.flatMap {
                val value = read<Any>(props, it)

                if (value is MappedArgument.Value) {
                    listOf(Pair(it, value.value))
                } else {
                    listOf()
                }
            }

            return ctor.callBy(mapOf(*args.toTypedArray()))
        }

        fun <T : FastConfig> loadFromAbsoluteClasspath(clazz: KClass<T>, path: String = defaultConfigFile): T =
                loadFromRelativeClasspath(clazz, "/$path")

        fun <T : FastConfig> loadFromRelativeClasspath(clazz: KClass<T>, relativePath: String = defaultConfigFile): T =
                loadFromStream(clazz, clazz.java.getResourceAsStream(relativePath))

        fun <T : FastConfig> loadFromStream(clazz: KClass<T>, stream: InputStream): T {
            val props = Properties()
            props.load(stream)

            return loadFromProperties(clazz, props)
        }

        fun <T : FastConfig> loadFromReader(clazz: KClass<T>, reader: Reader): T {
            val props = Properties()
            props.load(reader)

            return loadFromProperties(clazz, props)
        }

        fun <T : FastConfig> loadFromFile(clazz: KClass<T>, file: File): T =
                loadFromStream(clazz, file.inputStream())

        fun <T : FastConfig> loadFromFile(clazz: KClass<T>, file: String = defaultConfigFile): T =
                loadFromFile(clazz, File(file))
    }

    open val comment = "Generated by fast-config: https://github.com/Fylipp/fast-config"

    fun saveToProperties(): Properties {
        val props = Properties()

        javaClass.kotlin.memberProperties.forEach {
            write(it.get(this), props, it)
        }

        return props
    }

    fun saveToStream(stream: OutputStream) = saveToProperties().store(stream, comment)

    fun saveToStream(writer: Writer) = saveToProperties().store(writer, comment)

    fun saveToFile(file: File) = saveToStream(file.outputStream())

    fun saveToFile(file: String = defaultConfigFile) = saveToFile(File(file))
}
